### ISSUE TITLE
It easy:)

### ISSUE THREAD

**Issue by lab313ru** [zznop/jump#1]
I've solved it. And I want to write an article about that.

**Comment by zznop** [comment]
You and about 30 other people. The source code will be published in a month or so. Thanks for checking it out.

**Comment by lab313ru** [comment]
https://habr.com/ru/post/448500/

Brandon Miller <notifications@github.com> 17 апреля 2019 г. 22:55:22 написал:

**Comment by zznop** [comment]
Good stuff!
